#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------
#   File Name: int2ip
#      Author: Zhao Yanbai
#              2021-01-19 13:14:17 Tuesday CST
# Description: none
# ------------------------------------------------------------------------


import socket
import struct
import sys

if len(sys.argv) == 1 :
    print("{0} <intip1> <intip2> ...".format(sys.argv[0]))

for ipint in sys.argv[1:] :
    try :
        ipint = int(ipint)
    except :
        print("{0}: is not digital".format(ipint))
        continue

    ip1 = socket.inet_ntoa(struct.pack('I',ipint))
    ip2 = socket.inet_ntoa(struct.pack('I',socket.htonl(ipint)))

    print("{0}: {1}      {2}".format(ipint, ip1, ip2))
