if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=ucs-bom,utf-8,latin1
endif
set nocompatible	" Use Vim defaults (much better!)
set bs=indent,eol,start		" allow backspacing over everything in insert mode
"set ai			" always set autoindenting on
"set backup		" keep a backup file
set viminfo='20,\"50	" read/write a .viminfo file, don't store more
			" than 50 lines of registers
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time

" Only do this part when compiled with support for autocommands
if has("autocmd")
  augroup fedora
  autocmd!
  " In text files, always limit the width of text to 78 characters
  " autocmd BufRead *.txt set tw=78
  " When editing a file, always jump to the last cursor position
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line ("'\"") <= line("$") |
  \   exe "normal! g'\"" |
  \ endif
  " don't write swapfile on most commonly used directories for NFS mounts or USB sticks
  autocmd BufNewFile,BufReadPre /media/*,/mnt/* set directory=~/tmp,/var/tmp,/tmp
  " start with spec file template
  autocmd BufNewFile *.spec 0r /usr/share/vim/vimfiles/template.spec
  augroup END
endif

if has("cscope") && filereadable("/usr/bin/cscope")
   set csprg=/usr/bin/cscope
   set csto=0
   set cst
   set nocsverb
   " add any database in current directory
   if filereadable("cscope.out")
      cs add cscope.out
   " else add database pointed to by environment
   elseif $CSCOPE_DB != ""
      cs add $CSCOPE_DB
   endif
   set csverb
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

filetype plugin on

if &term=="xterm"
     set t_Co=8
     set t_Sb=[4%dm
     set t_Sf=[3%dm
endif

" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"

" ========================================
" SELF SETTING
" ========================================
set number        " 显示行号
" set autoindent    " 自动对齐
set smartindent

set tabstop=4     " TAB的宽度
set shiftwidth=4
set expandtab     " TAB用空格代替，否则可用 set noexpandtab
set cursorline

"hi CursorLine ctermbg=lightcyan cterm=BOLD
"set cursorcolumn
"hi CursorColumn ctermbg=lightgreen cterm=BOLD
set viminfo='1000,<500

" 以下是让mac vim支持中文输入
set encoding=utf-8  " 默认UTF-8
set fenc=utf-8      " 默认以UTF-8新建文件
set fileencodings=utf-8,cp936   " 打开文件编码按顺序匹配
set nobomb          " 


"为不同的文件类型设置不同的空格数替换TAB
autocmd FileType php,python,h,c,java,perl,shell,bash,vim,ruby,cc,cpp set ai
autocmd FileType php,python,h,c,java,perl,shell,bash,vim,ruby,cc,cpp set sw=4
autocmd FileType php,python,h,c,java,perl,shell,bash,vim,ruby,cc,cpp set ts=4
autocmd FileType php,python,h,c,java,perl,shell,bash,vim,ruby,cc,cpp set sts=4
autocmd FileType php,python,h,c,java,perl,shell,bash,vim,ruby,cc,cpp set expandtab


"golang默认使用TAB
"autocmd FileType go set ai
"autocmd FileType go set tabstop=4
"autocmd FileType go set shiftwidth=4
"autocmd FileType go set noexpandtab

autocmd FileType asm set ai
autocmd FileType asm set tabstop=4
autocmd FileType asm set shiftwidth=4
autocmd FileType asm set expandtab

" 连续按两次jj表示按ESC，进入命令模式
imap jj <Esc>


" set paste 会使 imap jj <Esc>失效
"set paste


filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'
"Plugin 'Valloric/YouCompleteMe'
"Plugin 'Lokaltog/vim-powerline'
"Plugin 'scrooloose/nerdtree'
call vundle#end()
filetype plugin indent on

" youcompleteme插件相关配置
let g:ycm_global_ycm_extra_conf = "~/.vim/bundle/YouCompleteMe/third_party/ycmd/.ycm_extra_conf.py"
" 设置回车为补全确认键
let g:ycm_key_list_stop_completion = ['<CR>']

" vim-powerline插件相关配置
set laststatus=2   " Always show the statusline
set encoding=utf-8 " Necessary to show Unicode glyphs
set t_Co=256
let g:Powerline_symbols= 'unicode'

" NERDTree 插件的相关配置
"F2开启和关闭树"
map <F2> :NERDTreeToggle<CR>
let NERDTreeChDirMode=1
"显示书签"
let NERDTreeShowBookmarks=1
"设置忽略文件类型"
let NERDTreeIgnore=['\~$', '\.pyc$', '\.swp$']
"窗口大小"
let NERDTreeWinSize=25

"let g:indentLine_setColors = 0
"let g:indentLine_color_term = 239
"let g:indentLine_bgcolor_term = 202
"let g:indentLine_bgcolor_gui = '#FF5F00'
"let g:indentLine_char = '|'
let g:indentLine_color_term = 239
"let g:indentLine_char_list = ['|', '¦', '┆', '┊']
"let g:indentLine_enabled=1
let g:indentLine_char='┆'
let g:indentLine_enabled = 1
let g:indentLine_showFirstIndentLevel = 1
