// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sample.proto

/*
Package sample is a generated protocol buffer package.

It is generated from these files:
	sample.proto

It has these top-level messages:
	SampleData
*/
package sample

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SampleType int32

const (
	SampleType_SAMPLE_TYPE_RAW         SampleType = 1
	SampleType_SAMPLE_TYPE_LIGHT       SampleType = 2
	SampleType_SAMPLE_TYPE_TEMPERATURE SampleType = 3
	SampleType_SAMPLE_TYPE_HUMIDITY    SampleType = 4
	SampleType_SAMPLE_TYPE_TEST        SampleType = 5
)

var SampleType_name = map[int32]string{
	1: "SAMPLE_TYPE_RAW",
	2: "SAMPLE_TYPE_LIGHT",
	3: "SAMPLE_TYPE_TEMPERATURE",
	4: "SAMPLE_TYPE_HUMIDITY",
	5: "SAMPLE_TYPE_TEST",
}
var SampleType_value = map[string]int32{
	"SAMPLE_TYPE_RAW":         1,
	"SAMPLE_TYPE_LIGHT":       2,
	"SAMPLE_TYPE_TEMPERATURE": 3,
	"SAMPLE_TYPE_HUMIDITY":    4,
	"SAMPLE_TYPE_TEST":        5,
}

func (x SampleType) Enum() *SampleType {
	p := new(SampleType)
	*p = x
	return p
}
func (x SampleType) String() string {
	return proto.EnumName(SampleType_name, int32(x))
}
func (x *SampleType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SampleType_value, data, "SampleType")
	if err != nil {
		return err
	}
	*x = SampleType(value)
	return nil
}
func (SampleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SampleData struct {
	Title            *string            `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Type             *SampleType        `protobuf:"varint,2,opt,name=type,enum=sample.SampleType" json:"type,omitempty"`
	Data             []float64          `protobuf:"fixed64,3,rep,name=data" json:"data,omitempty"`
	Source           *SampleData_Source `protobuf:"group,4,opt,name=Source,json=source" json:"source,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SampleData) Reset()                    { *m = SampleData{} }
func (m *SampleData) String() string            { return proto.CompactTextString(m) }
func (*SampleData) ProtoMessage()               {}
func (*SampleData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SampleData) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *SampleData) GetType() SampleType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return SampleType_SAMPLE_TYPE_RAW
}

func (m *SampleData) GetData() []float64 {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SampleData) GetSource() *SampleData_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type SampleData_Source struct {
	Band             *string `protobuf:"bytes,5,req,name=band" json:"band,omitempty"`
	Version          *string `protobuf:"bytes,6,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SampleData_Source) Reset()                    { *m = SampleData_Source{} }
func (m *SampleData_Source) String() string            { return proto.CompactTextString(m) }
func (*SampleData_Source) ProtoMessage()               {}
func (*SampleData_Source) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *SampleData_Source) GetBand() string {
	if m != nil && m.Band != nil {
		return *m.Band
	}
	return ""
}

func (m *SampleData_Source) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*SampleData)(nil), "sample.SampleData")
	proto.RegisterType((*SampleData_Source)(nil), "sample.SampleData.Source")
	proto.RegisterEnum("sample.SampleType", SampleType_name, SampleType_value)
}

func init() { proto.RegisterFile("sample.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xc9, 0xfa, 0x47, 0x76, 0x11, 0x8d, 0xd7, 0x8a, 0x51, 0x5f, 0x8a, 0x0f, 0x12, 0x7c,
	0x28, 0xb8, 0x07, 0xdf, 0x0b, 0x0b, 0xae, 0xb0, 0x42, 0x49, 0x33, 0x64, 0x4f, 0x23, 0xba, 0x3c,
	0x0c, 0xe6, 0x5a, 0xda, 0x28, 0xec, 0x03, 0xf8, 0xe1, 0xfc, 0x56, 0xd2, 0x74, 0x4a, 0xf7, 0x76,
	0xce, 0xef, 0xde, 0x73, 0x92, 0x0b, 0xa7, 0xad, 0xfe, 0xa8, 0xb7, 0x26, 0xa9, 0x9b, 0xca, 0x56,
	0x18, 0xf6, 0xee, 0xfe, 0x87, 0x00, 0x94, 0x4e, 0x4e, 0xb5, 0xd5, 0x18, 0x41, 0x60, 0x37, 0x76,
	0x6b, 0x18, 0x89, 0x09, 0x1f, 0xcb, 0xde, 0xe0, 0x03, 0xf8, 0x76, 0x5f, 0x1b, 0x36, 0x8a, 0x09,
	0x3f, 0x9b, 0x60, 0x72, 0x68, 0xea, 0x73, 0x6a, 0x5f, 0x1b, 0xe9, 0xe6, 0x88, 0xe0, 0xaf, 0xb5,
	0xd5, 0xcc, 0x8b, 0x3d, 0x4e, 0xa4, 0xd3, 0xf8, 0x04, 0x61, 0x5b, 0x7d, 0x36, 0xef, 0x86, 0xf9,
	0x31, 0xe1, 0x30, 0xb9, 0x39, 0x4e, 0x77, 0xaf, 0x26, 0xa5, 0x5b, 0x90, 0x87, 0xc5, 0xdb, 0x67,
	0x08, 0x7b, 0xd2, 0x15, 0xbe, 0xe9, 0xdd, 0x9a, 0x05, 0xf1, 0x88, 0x8f, 0xa5, 0xd3, 0xc8, 0xe0,
	0xe4, 0xcb, 0x34, 0xed, 0xa6, 0xda, 0xb1, 0xd0, 0xe1, 0x3f, 0xfb, 0xf8, 0xfd, 0x7f, 0x4b, 0xf7,
	0x27, 0xbc, 0x84, 0xf3, 0x32, 0xcd, 0x8b, 0xb9, 0x58, 0xa9, 0x65, 0x21, 0x56, 0x32, 0x7d, 0xa5,
	0x04, 0xaf, 0xe0, 0x62, 0x08, 0xe7, 0xd9, 0xcb, 0x4c, 0xd1, 0x11, 0xde, 0xc1, 0xf5, 0x10, 0x2b,
	0x91, 0x17, 0x42, 0xa6, 0x6a, 0x21, 0x05, 0xf5, 0x90, 0x41, 0x34, 0x1c, 0xce, 0x16, 0x79, 0x36,
	0xcd, 0xd4, 0x92, 0xfa, 0x18, 0x01, 0x3d, 0x8e, 0x95, 0x8a, 0x06, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x7c, 0x62, 0x65, 0x58, 0x6a, 0x01, 0x00, 0x00,
}
